### ISSUE TITLE
Ambiguous licences

### ISSUE THREAD

**Issue by cstrobbe** [tlhunter/node-easyxml#7]
Would it be possible to specify which versions of BSD and GPL you are using? 
BSD exists in at least three flavours:
- the [BSD 3-clause licence (aka modified BSD)](http://directory.fsf.org/wiki/License:BSD_3Clause);
- the [original BSD aka 4-clause licence](http://directory.fsf.org/wiki/License:BSD_4Clause) (no longer recommended by the FSF);
- [Clear BSD](http://directory.fsf.org/wiki/License:ClearBSD).

To which of the following does "GPL" refer?
- [GNU GPL v. 2.0](http://www.gnu.org/licenses/old-licenses/gpl-2.0.html): the FSF does no longer recommend this version; it is not compatible with GNU GPL v. 3.0;
- [GNU GPL v. 3.0](http://www.gnu.org/licenses/gpl.html): the latest version;
- [GNU LGPL v. 2.1](http://www.gnu.org/licenses/lgpl.html): less strong than GPL; designed to allow linking with non-GPL software (e.g. you can develop LGPL'ed extensions for LibreOffice);
- [GNU AGPL v. 3.0](http://www.gnu.org/licenses/agpl.html): like LGPL but with a clause that is relevant to software that runs on a server.

I would appreciate it if you could clarify this.

**Comment by tlhunter** [comment]
Good call. There's even a standard for adding license to package.json (though idk if it handles dual licenses). I'll do some research and get back to this.
