### ISSUE TITLE
Incorrect nesting of child nodes when singularizeChildren is false

### ISSUE THREAD

**Issue by andrew-wharton** [tlhunter/node-easyxml#8]
Created a unit test demonstrating the incorrect behaviour -> https://github.com/andrew-wharton/node-easyxml/commit/c53ff3085521cc6f01dcbf7e7893473078ce3f15

Should I create a pull request for you to add this unit test so the problem can be fixed? I'm not sure how to go about fixing it myself unfortunately...

**Comment by tlhunter** [comment]
This is fixed in a PR. Will bump MAJOR versions. Going to make some more MINOR changes then merge.

**Comment by andrew-wharton** [comment]
Cool. Thanks!
